/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostasIndexRouteImport } from './routes/propostas.index'
import { Route as PipelineIndexRouteImport } from './routes/pipeline.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as PropostasNovaRouteImport } from './routes/propostas.nova'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as PipelineCardCardIdRouteImport } from './routes/pipeline.card.$cardId'
import { Route as ClienteAcompanhamentoTokenRouteImport } from './routes/cliente.acompanhamento.$token'
import { Route as ApiPublicPTokenRouteImport } from './routes/api/public/p.$token'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIndexRoute = PropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineIndexRoute = PipelineIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PipelineRoute,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasNovaRoute = PropostasNovaRouteImport.update({
  id: '/propostas/nova',
  path: '/propostas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineCardCardIdRoute = PipelineCardCardIdRouteImport.update({
  id: '/card/$cardId',
  path: '/card/$cardId',
  getParentRoute: () => PipelineRoute,
} as any)
const ClienteAcompanhamentoTokenRoute =
  ClienteAcompanhamentoTokenRouteImport.update({
    id: '/cliente/acompanhamento/$token',
    path: '/cliente/acompanhamento/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPTokenRoute = ApiPublicPTokenRouteImport.update({
  id: '/api/public/p/$token',
  path: '/api/public/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/propostas/': typeof PropostasIndexRoute
  '/cliente/acompanhamento/$token': typeof ClienteAcompanhamentoTokenRoute
  '/pipeline/card/$cardId': typeof PipelineCardCardIdRoute
  '/api/public/p/$token': typeof ApiPublicPTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes': typeof ClientesIndexRoute
  '/pipeline': typeof PipelineIndexRoute
  '/propostas': typeof PropostasIndexRoute
  '/cliente/acompanhamento/$token': typeof ClienteAcompanhamentoTokenRoute
  '/pipeline/card/$cardId': typeof PipelineCardCardIdRoute
  '/api/public/p/$token': typeof ApiPublicPTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/cadastro': typeof CadastroRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRouteWithChildren
  '/produtos': typeof ProdutosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes/': typeof ClientesIndexRoute
  '/pipeline/': typeof PipelineIndexRoute
  '/propostas/': typeof PropostasIndexRoute
  '/cliente/acompanhamento/$token': typeof ClienteAcompanhamentoTokenRoute
  '/pipeline/card/$cardId': typeof PipelineCardCardIdRoute
  '/api/public/p/$token': typeof ApiPublicPTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/financeiro'
    | '/login'
    | '/pipeline'
    | '/produtos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/clientes/$id'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/clientes/'
    | '/pipeline/'
    | '/propostas/'
    | '/cliente/acompanhamento/$token'
    | '/pipeline/card/$cardId'
    | '/api/public/p/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/financeiro'
    | '/login'
    | '/produtos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/clientes/$id'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/clientes'
    | '/pipeline'
    | '/propostas'
    | '/cliente/acompanhamento/$token'
    | '/pipeline/card/$cardId'
    | '/api/public/p/$token'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/cadastro'
    | '/configuracoes'
    | '/financeiro'
    | '/login'
    | '/pipeline'
    | '/produtos'
    | '/recuperar-senha'
    | '/relatorios'
    | '/reset-password'
    | '/clientes/$id'
    | '/propostas/$id'
    | '/propostas/nova'
    | '/clientes/'
    | '/pipeline/'
    | '/propostas/'
    | '/cliente/acompanhamento/$token'
    | '/pipeline/card/$cardId'
    | '/api/public/p/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  CadastroRoute: typeof CadastroRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRouteWithChildren
  ProdutosRoute: typeof ProdutosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ClientesIdRoute: typeof ClientesIdRoute
  PropostasIdRoute: typeof PropostasIdRoute
  PropostasNovaRoute: typeof PropostasNovaRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  PropostasIndexRoute: typeof PropostasIndexRoute
  ClienteAcompanhamentoTokenRoute: typeof ClienteAcompanhamentoTokenRoute
  ApiPublicPTokenRoute: typeof ApiPublicPTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/': {
      id: '/propostas/'
      path: '/propostas'
      fullPath: '/propostas/'
      preLoaderRoute: typeof PropostasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/': {
      id: '/pipeline/'
      path: '/'
      fullPath: '/pipeline/'
      preLoaderRoute: typeof PipelineIndexRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/nova': {
      id: '/propostas/nova'
      path: '/propostas/nova'
      fullPath: '/propostas/nova'
      preLoaderRoute: typeof PropostasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline/card/$cardId': {
      id: '/pipeline/card/$cardId'
      path: '/card/$cardId'
      fullPath: '/pipeline/card/$cardId'
      preLoaderRoute: typeof PipelineCardCardIdRouteImport
      parentRoute: typeof PipelineRoute
    }
    '/cliente/acompanhamento/$token': {
      id: '/cliente/acompanhamento/$token'
      path: '/cliente/acompanhamento/$token'
      fullPath: '/cliente/acompanhamento/$token'
      preLoaderRoute: typeof ClienteAcompanhamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/p/$token': {
      id: '/api/public/p/$token'
      path: '/api/public/p/$token'
      fullPath: '/api/public/p/$token'
      preLoaderRoute: typeof ApiPublicPTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PipelineRouteChildren {
  PipelineIndexRoute: typeof PipelineIndexRoute
  PipelineCardCardIdRoute: typeof PipelineCardCardIdRoute
}

const PipelineRouteChildren: PipelineRouteChildren = {
  PipelineIndexRoute: PipelineIndexRoute,
  PipelineCardCardIdRoute: PipelineCardCardIdRoute,
}

const PipelineRouteWithChildren = PipelineRoute._addFileChildren(
  PipelineRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  CadastroRoute: CadastroRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRouteWithChildren,
  ProdutosRoute: ProdutosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ClientesIdRoute: ClientesIdRoute,
  PropostasIdRoute: PropostasIdRoute,
  PropostasNovaRoute: PropostasNovaRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  PropostasIndexRoute: PropostasIndexRoute,
  ClienteAcompanhamentoTokenRoute: ClienteAcompanhamentoTokenRoute,
  ApiPublicPTokenRoute: ApiPublicPTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
