/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostasIndexRouteImport } from './routes/propostas.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as PropostasNovaRouteImport } from './routes/propostas.nova'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as ClienteAcompanhamentoTokenRouteImport } from './routes/cliente.acompanhamento.$token'
import { Route as ApiPublicPTokenRouteImport } from './routes/api/public/p.$token'

const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIndexRoute = PropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasNovaRoute = PropostasNovaRouteImport.update({
  id: '/propostas/nova',
  path: '/propostas/nova',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClienteAcompanhamentoTokenRoute =
  ClienteAcompanhamentoTokenRouteImport.update({
    id: '/cliente/acompanhamento/$token',
    path: '/cliente/acompanhamento/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPTokenRoute = ApiPublicPTokenRouteImport.update({
  id: '/api/public/p/$token',
  path: '/api/public/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/pipeline': typeof PipelineRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes/': typeof ClientesIndexRoute
  '/propostas/': typeof PropostasIndexRoute
  '/cliente/acompanhamento/$token': typeof ClienteAcompanhamentoTokenRoute
  '/api/public/p/$token': typeof ApiPublicPTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/pipeline': typeof PipelineRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes': typeof ClientesIndexRoute
  '/propostas': typeof PropostasIndexRoute
  '/cliente/acompanhamento/$token': typeof ClienteAcompanhamentoTokenRoute
  '/api/public/p/$token': typeof ApiPublicPTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/pipeline': typeof PipelineRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/propostas/nova': typeof PropostasNovaRoute
  '/clientes/': typeof ClientesIndexRoute
  '/propostas/': typeof PropostasIndexRoute
  '/cliente/acompanhamento/$token': typeof ClienteAcompanhamentoTokenRoute
  '/api/public/p/$token': typeof ApiPublicPTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/pipeline'
    | '/produtos'
    | '/relatorios'
    | '/clientes/$id'
    | '/propostas/nova'
    | '/clientes/'
    | '/propostas/'
    | '/cliente/acompanhamento/$token'
    | '/api/public/p/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/pipeline'
    | '/produtos'
    | '/relatorios'
    | '/clientes/$id'
    | '/propostas/nova'
    | '/clientes'
    | '/propostas'
    | '/cliente/acompanhamento/$token'
    | '/api/public/p/$token'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/pipeline'
    | '/produtos'
    | '/relatorios'
    | '/clientes/$id'
    | '/propostas/nova'
    | '/clientes/'
    | '/propostas/'
    | '/cliente/acompanhamento/$token'
    | '/api/public/p/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  PipelineRoute: typeof PipelineRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ClientesIdRoute: typeof ClientesIdRoute
  PropostasNovaRoute: typeof PropostasNovaRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  PropostasIndexRoute: typeof PropostasIndexRoute
  ClienteAcompanhamentoTokenRoute: typeof ClienteAcompanhamentoTokenRoute
  ApiPublicPTokenRoute: typeof ApiPublicPTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/': {
      id: '/propostas/'
      path: '/propostas'
      fullPath: '/propostas/'
      preLoaderRoute: typeof PropostasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/nova': {
      id: '/propostas/nova'
      path: '/propostas/nova'
      fullPath: '/propostas/nova'
      preLoaderRoute: typeof PropostasNovaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cliente/acompanhamento/$token': {
      id: '/cliente/acompanhamento/$token'
      path: '/cliente/acompanhamento/$token'
      fullPath: '/cliente/acompanhamento/$token'
      preLoaderRoute: typeof ClienteAcompanhamentoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/p/$token': {
      id: '/api/public/p/$token'
      path: '/api/public/p/$token'
      fullPath: '/api/public/p/$token'
      preLoaderRoute: typeof ApiPublicPTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  PipelineRoute: PipelineRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  ClientesIdRoute: ClientesIdRoute,
  PropostasNovaRoute: PropostasNovaRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  PropostasIndexRoute: PropostasIndexRoute,
  ClienteAcompanhamentoTokenRoute: ClienteAcompanhamentoTokenRoute,
  ApiPublicPTokenRoute: ApiPublicPTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
